### ISSUE TITLE
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

### ISSUE THREAD

**Issue by ofn1** [ocaballeror/jeepney-objects#3]
Hi,
    Got error with python3.6 and python3.8.
    python3.6:
```
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jeepney import DBusAddress
>>> from jeepney_objects import DBusObject
>>>
>>> dbobject = DBusObject()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/jeepney_objects/dbus_object.py", line 50, in __init__
    self.conn = connect_and_authenticate(bus='SESSION')
  File "/usr/local/lib/python3.6/dist-packages/jeepney/integrate/blocking.py", line 6, in connect_and_authenticate
    conn = open_dbus_connection(bus)
  File "/usr/local/lib/python3.6/dist-packages/jeepney/io/blocking.py", line 243, in open_dbus_connection
    bus_addr = get_bus(bus)
  File "/usr/local/lib/python3.6/dist-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/usr/local/lib/python3.6/dist-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
```
    python3.8:
```
Python 3.8.0 (default, Feb 25 2021, 22:10:10)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jeepney import DBusAddress
>>> from jeepney_objects import DBusObject
>>> dbobject = DBusObject()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/jeepney_objects/dbus_object.py", line 50, in __init__
    self.conn = connect_and_authenticate(bus='SESSION')
  File "/usr/local/lib/python3.8/dist-packages/jeepney/integrate/blocking.py", line 6, in connect_and_authenticate
    conn = open_dbus_connection(bus)
  File "/usr/local/lib/python3.8/dist-packages/jeepney/io/blocking.py", line 243, in open_dbus_connection
    bus_addr = get_bus(bus)
  File "/usr/local/lib/python3.8/dist-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/usr/local/lib/python3.8/dist-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
```

**Comment by ofn1** [comment]
It's solved by install dbux-x11

**Comment by ocaballeror** [comment]
Good to know :+1:
